[theme]
base = "light"
primaryColor = "#E75C37"
backgroundColor = "#F7F6F2"
secondaryBackgroundColor = "#ECEBE6"
textColor = "#202C37"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
